name: Run test
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    push:
        branches:
            - main
            - test/**
    pull_request:
    workflow_dispatch:

concurrency:
    group: |
        test-${{
            startsWith(github.ref_name, 'test') && github.ref_name ||
            github.run_id
        }}
    cancel-in-progress: true

jobs:
    run:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}
                  fetch-depth: 0

            - name: Use ccache
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                  create-symlink: true
                  
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            
            - name: Install tomlq
              run: cargo install tomlq
              
            - name: Query TOML with tomlq
              run: |
                tq 'install' --file dist/swift.toml                  

            - name: Install
              run: |
                tq '.scripts.install' --file dist/swift.toml | sed "1d;$d" | sh

            - name: Test
              run: |
                  chmod +x ./test/test.sh
                  ./test/test.sh
