name: Run test
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    push:
        branches:
            - main
            - test/**
    pull_request:
    workflow_dispatch:

concurrency:
    group: |
        test-${{
            startsWith(github.ref_name, 'test') && github.ref_name ||
            github.run_id
        }}
    cancel-in-progress: true

jobs:
    run:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}
                  fetch-depth: 0

            - name: Use ccache
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                  create-symlink: true
                  
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            
            - name: Install tomlq
              run: cargo install tomlq
              
            - name: Install
              run: |
                tq 'install' --file dist/swift.toml | sed -e "1s/^'''//" -e "\$s/'''$//" | bash               

            # - name: Check Swift version
            #   run: |
            #     chmod +x ./test/check_version.sh
            #     ./test/check_version.sh
            
            - name: Test
              run: |
                  chmod +x ./test/test.sh
                  ./test/test.sh
            # 生成された build.sh をアーティファクトとしてアップロード
            - name: Upload build.sh artifact
              uses: actions/upload-artifact@v3
              with:
                name: build-script
                path: build.sh
                
